### ISSUE TITLE
Wharf clone private repo fails.

### ISSUE THREAD

**Issue by be-ez** [be-ez/blog#9]
Wharf clone private repo fails. 

```bash
Wharf: task log for blog
Deploying blog
Task id: 9c3123f1-b36c-4ad0-992d-c919cbc96227
Task state: FAILURE
== Cloning ==
Cloning into '/app/repos/blog'...
fatal: could not read Username for 'https://github.com': No such device or address
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 375, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 632, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/wharf/tasks.py", line 125, in deploy
    run_process(key, ["git", "clone", git_url, app_repo_path])
  File "/app/wharf/tasks.py", line 111, in run_process
    raise Exception
Exception

**Comment by be-ez** [comment]
This is likey due to switching between docker and build packs. 

Try deleting the app or check your ssh key.
